/**
 * Generated by frontend/scripts/build-tokens.mjs
 * Source authoring tree: /tokens
 * Do not edit this file by hand.
 */

export const canonicalBrand = {
  navy: "#0f172a",
  blue: "#339fff",
  green: "#20c997",
  red: "#ff5d5d",
  gold: "#d4af37",
} as const;

/**
 * @deprecated Use canonicalBrand.* directly in new code.
 * Kept only for soft migration compatibility.
 */
export const legacyBrandAliases = {
  primary: canonicalBrand.blue,
  accent: canonicalBrand.green,
} as const;

export const colors = {
  navy: {
    "50": "#f0f4f8",
    "100": "#d9e2ec",
    "200": "#bcccdc",
    "300": "#9fb3c8",
    "400": "#829ab1",
    "500": "#627d98",
    "600": "#486581",
    "700": "#334e68",
    "800": "#243b53",
    "900": "#102a43",
  },
  blue: {
    "50": "#eff6ff",
    "100": "#dbeafe",
    "200": "#bfdbfe",
    "300": "#93c5fd",
    "400": "#60a5fa",
    "500": "#3b82f6",
    "600": "#2563eb",
    "700": "#1d4ed8",
    "800": "#1e40af",
    "900": "#1e3a8a",
  },
  green: {
    "50": "#f0fdf4",
    "100": "#dcfce7",
    "200": "#bbf7d0",
    "300": "#86efac",
    "400": "#4ade80",
    "500": "#22c55e",
    "600": "#16a34a",
    "700": "#15803d",
    "800": "#166534",
    "900": "#14532d",
  },
  heart: {
    "50": "#fef2f2",
    "100": "#fee2e2",
    "200": "#fecaca",
    "300": "#fca5a5",
    "400": "#f87171",
    "500": "#ef4444",
    "600": "#dc2626",
    "700": "#b91c1c",
    "800": "#991b1b",
    "900": "#7f1d1d",
  },
  gray: {
    "50": "#f9fafb",
    "100": "#f3f4f6",
    "200": "#e5e7eb",
    "300": "#d1d5db",
    "400": "#9ca3af",
    "500": "#6b7280",
    "600": "#4b5563",
    "700": "#374151",
    "800": "#1f2937",
    "900": "#111827",
  },
  semantic: {
    success: canonicalBrand.green,
    warning: "#f59e0b",
    error: canonicalBrand.red,
    info: canonicalBrand.blue,
  },
} as const;

export const spacing = {
  "0": "0",
  "1": "0.25rem",
  "2": "0.5rem",
  "3": "0.75rem",
  "4": "1rem",
  "5": "1.25rem",
  "6": "1.5rem",
  "8": "2rem",
  "10": "2.5rem",
  "12": "3rem",
  "16": "4rem",
  "20": "5rem",
  "24": "6rem",
  touch: "2.75rem",
  touchLarge: "3.5rem",
  button: {
    sm: "0.5rem 1rem",
    md: "0.75rem 1.5rem",
    lg: "1rem 2rem",
  },
  input: {
    sm: "0.5rem 0.75rem",
    md: "0.75rem 1rem",
    lg: "1rem 1.25rem",
  },
} as const;

export const typography = {
  fontFamily: {
    sans: ["Inter", "system-ui", "sans-serif"],
    mono: ["JetBrains Mono", "Consolas", "monospace"],
  },
  fontSize: {
    xs: "0.75rem",
    sm: "0.875rem",
    base: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    "5xl": "3rem",
  },
  fontWeight: {
    light: "300",
    normal: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
  },
  lineHeight: {
    tight: "1.25",
    snug: "1.375",
    normal: "1.5",
    relaxed: "1.625",
    loose: "2",
  },
  textStyles: {
    heading: {
      fontFamily: "Inter",
      fontWeight: "600",
      lineHeight: "1.25",
    },
    body: {
      fontFamily: "Inter",
      fontWeight: "400",
      lineHeight: "1.5",
    },
    caption: {
      fontFamily: "Inter",
      fontWeight: "400",
      lineHeight: "1.375",
      fontSize: "0.875rem",
    },
  },
} as const;

export const borderRadius = {
  none: "0px",
  sm: "0.125rem",
  base: "0.25rem",
  md: "0.375rem",
  lg: "0.5rem",
  xl: "0.75rem",
  "2xl": "1rem",
  full: "9999px",
} as const;

export const shadows = {
  sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
  base: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
  md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
} as const;

export const breakpoints = {
  sm: "640px",
  md: "768px",
  lg: "1024px",
  xl: "1280px",
  "2xl": "1536px",
} as const;

export const zIndex = {
  hide: -1,
  auto: "auto",
  base: 0,
  docked: 10,
  dropdown: 1000,
  sticky: 1100,
  banner: 1200,
  overlay: 1300,
  modal: 1400,
  popover: 1500,
  skipLink: 1600,
  toast: 1700,
  tooltip: 1800,
} as const;

export type ColorScale = keyof typeof colors.navy;
export type SpacingKey = keyof typeof spacing;
export type TypographySize = keyof typeof typography.fontSize;
export type TypographyWeight = keyof typeof typography.fontWeight;
