"""Tests for the Python dependency surface contract validator."""

from __future__ import annotations

from pathlib import Path

import pytest

from scripts.ci import check_python_dependency_surfaces as surfaces

REPO_ROOT = Path(__file__).resolve().parents[1]


def _write_lockfile(root: Path, surface: surfaces.DependencySurface) -> None:
    lock_path = root / surface.lockfile
    if surface.lockfile == "requirements-all.txt":
        lock_path.write_text("-r requirements.txt\npytest>=9.1.1\n", encoding="utf-8")
        return

    if surface.lockfile == "requirements-lock.txt":
        header_sources = "requirements-dev.in requirements.in"
    else:
        assert surface.source_file is not None
        header_sources = surface.source_file

    body = "" if surface.allow_empty_lock else "example==1.0.0\n"
    directive = "".join(f"{item}\n\n" for item in surface.allow_lock_directives)
    lock_path.write_text(
        "\n".join(
            (
                "#",
                "# This file is autogenerated by pip-compile with Python 3.13",
                "# by the following command:",
                "#",
                (
                    "#    pip-compile --allow-unsafe --no-emit-index-url "
                    f"--output-file={surface.lockfile} {header_sources}"
                ),
                "#",
                directive + body,
            )
        ),
        encoding="utf-8",
    )


def _write_valid_contract_repo(root: Path) -> None:
    for directory in (
        root / ".github" / "actions" / "python-setup",
        root / ".github" / "workflows",
        root / "docs" / "contracts",
        root / "docs",
        root / "scripts",
        root / "scripts" / "ci",
    ):
        directory.mkdir(parents=True, exist_ok=True)

    all_surface_files = sorted(surfaces._known_requirement_surfaces())
    for surface in surfaces.DEPENDENCY_SURFACES:
        if surface.source_file is not None:
            (root / surface.source_file).write_text("example>=1.0.0\n", encoding="utf-8")
        _write_lockfile(root, surface)

    contract_body = "\n".join(
        [
            "# Python Dependency Surfaces",
            "Noncanonical Aggregate Install Surfaces",
            "scripts/ci/check_python_dependency_surfaces.py",
            *all_surface_files,
        ]
    )
    (root / surfaces.CONTRACT_DOC).write_text(contract_body, encoding="utf-8")
    for doc_path in (surfaces.DEPENDENCY_DOC, surfaces.REQUIREMENTS_GUIDE):
        (root / doc_path).write_text(
            "\n".join(
                (
                    str(surfaces.CONTRACT_DOC),
                    "scripts/ci/check_python_dependency_surfaces.py",
                    "verify_requirements.py",
                )
            ),
            encoding="utf-8",
        )

    _write_python_setup_action(root)
    (root / surfaces.PIP_AUDIT_HELPER).write_text(
        "\n".join(
            surface.lockfile
            for surface in surfaces.DEPENDENCY_SURFACES
            if surface.pip_audit_required
        ),
        encoding="utf-8",
    )
    (root / surfaces.DEPENDENCY_SUBMISSION_WORKFLOW).write_text(
        "\n".join(
            surface.lockfile
            for surface in surfaces.DEPENDENCY_SURFACES
            if surface.dependency_submission_required
        ),
        encoding="utf-8",
    )


def _write_python_setup_action(root: Path, extra_case_labels: tuple[str, ...] = ()) -> None:
    profile_labels = (
        "runtime",
        "runtime-dev",
        "runtime-test",
        "ci-test",
        "ci-lite",
        "rag-vector",
        *extra_case_labels,
    )
    case_lines = "\n".join(f"            {profile}) ;;" for profile in profile_labels)
    (root / surfaces.PYTHON_SETUP_ACTION).write_text(
        (
            "# Mention requirements-data, requirements-evals, and rag-vector-cpu in a comment.\n"
            'case "$selected_profile" in\n'
            f"{case_lines}\n"
            "            *) ;;\n"
            "          esac\n"
        ),
        encoding="utf-8",
    )


def test_dependency_surface_contract_accepts_repo_contract() -> None:
    assert surfaces.validate_repo(REPO_ROOT) == []


def test_dependency_surface_contract_requires_all_managed_surfaces(tmp_path: Path) -> None:
    _write_valid_contract_repo(tmp_path)
    (tmp_path / "requirements-docker-runtime.txt").unlink()

    errors = surfaces.validate_repo(tmp_path)

    assert errors == ["Missing required dependency policy file: requirements-docker-runtime.txt."]


def test_dependency_surface_contract_rejects_unknown_surface(tmp_path: Path) -> None:
    _write_valid_contract_repo(tmp_path)
    (tmp_path / "requirements-surprise.txt").write_text("example==1.0.0\n", encoding="utf-8")

    errors = surfaces.validate_repo(tmp_path)

    assert errors == [
        "Unknown root requirements surfaces are not in the registry: "
        "['requirements-surprise.txt']."
    ]


def test_dependency_surface_contract_rejects_local_manual_shared_profile(
    tmp_path: Path,
) -> None:
    _write_valid_contract_repo(tmp_path)
    _write_python_setup_action(tmp_path, extra_case_labels=("data", "evals", "rag-vector-cpu"))

    errors = surfaces.validate_repo(tmp_path)

    assert any("'data'" in error for error in errors)
    assert any("'evals'" in error for error in errors)
    assert any("'rag-vector-cpu'" in error for error in errors)


def test_dependency_surface_contract_ignores_local_manual_names_outside_profile_cases(
    tmp_path: Path,
) -> None:
    _write_valid_contract_repo(tmp_path)

    errors = surfaces.validate_repo(tmp_path)

    assert errors == []


def test_dependency_surface_contract_rejects_missing_doc_mirror(tmp_path: Path) -> None:
    _write_valid_contract_repo(tmp_path)
    contract_path = tmp_path / surfaces.CONTRACT_DOC
    contract_path.write_text(
        contract_path.read_text(encoding="utf-8").replace("requirements-evals.txt\n", ""),
        encoding="utf-8",
    )

    errors = surfaces.validate_repo(tmp_path)

    assert errors == [
        f"{surfaces.CONTRACT_DOC}: missing dependency surface requirements-evals.txt."
    ]


def test_dependency_surface_contract_rejects_missing_pip_audit_coverage(
    tmp_path: Path,
) -> None:
    _write_valid_contract_repo(tmp_path)
    audit_helper = tmp_path / surfaces.PIP_AUDIT_HELPER
    audit_helper.write_text(
        audit_helper.read_text(encoding="utf-8").replace("requirements-data.txt\n", ""),
        encoding="utf-8",
    )

    errors = surfaces.validate_repo(tmp_path)

    assert errors == [
        f"{surfaces.PIP_AUDIT_HELPER}: missing pip-audit coverage for requirements-data.txt."
    ]


def test_dependency_surface_contract_rejects_missing_dependency_submission_coverage(
    tmp_path: Path,
) -> None:
    _write_valid_contract_repo(tmp_path)
    submission_workflow = tmp_path / surfaces.DEPENDENCY_SUBMISSION_WORKFLOW
    submission_workflow.write_text(
        submission_workflow.read_text(encoding="utf-8").replace("requirements-dev.txt\n", ""),
        encoding="utf-8",
    )

    errors = surfaces.validate_repo(tmp_path)

    assert errors == [
        f"{surfaces.DEPENDENCY_SUBMISSION_WORKFLOW}: missing dependency submission coverage "
        "for requirements-dev.txt."
    ]


def test_dependency_surface_contract_rejects_non_exact_compiled_entry(tmp_path: Path) -> None:
    _write_valid_contract_repo(tmp_path)
    (tmp_path / "requirements.txt").write_text(
        "\n".join(
            (
                "#",
                "# This file is autogenerated by pip-compile with Python 3.13",
                "# by the following command:",
                "#",
                "#    pip-compile --allow-unsafe --no-emit-index-url "
                "--output-file=requirements.txt requirements.in",
                "#",
                "fastapi>=0.122.0",
            )
        ),
        encoding="utf-8",
    )

    errors = surfaces.validate_repo(tmp_path)

    assert errors == ["requirements.txt: compiled entry must be exact-pinned: 'fastapi>=0.122.0'."]


def test_verify_requirements_wrapper_runs_surface_validator(
    capsys: pytest.CaptureFixture[str],
) -> None:
    import verify_requirements

    result = verify_requirements.main(["--repo-root", str(REPO_ROOT)])

    assert result == 0
    assert (
        "PASS: Python dependency surfaces match the canonical contract." in capsys.readouterr().out
    )
