import SwiftUI

// MARK: - Color Assets Extension
extension Color {
    // MARK: - Brand Colors
    // Note: navy, appPrimary, accent, gold are auto-generated by Xcode from Assets.xcassets
    // Only define custom colors here that don't exist in asset catalog
    static let heart = Color("HeartRed")

    // MARK: - Semantic Colors
    static let success = Color(hex: "#10B981")
    static let warning = Color(hex: "#F59E0B")
    static let error = Color(hex: "#EF4444")
    static let info = Color(hex: "#3B82F6")

    // MARK: - Surface Colors
    static let surface = Color.gray.opacity(0.1)
    static let surfaceElevated = Color.white.opacity(0.1)
    static let surfaceHighlight = Color.white.opacity(0.25)

    // MARK: - Text Colors
    static let textPrimary = Color.white
    static let textSecondary = Color.white.opacity(0.8)
    static let textTertiary = Color.white.opacity(0.6)

    /// Maps backend segment color names to canonical semantic UI colors.
    static func segmentSemanticColor(from colorString: String) -> Color {
        switch colorString.lowercased() {
        case "green":
            return .success
        case "red":
            return .heart
        case "orange", "yellow":
            return .warning
        case "blue", "purple":
            return .appPrimary
        default:
            return .textTertiary
        }
    }
}

// MARK: - Color Hex Initializer
extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 3: // RGB (12-bit)
            (a, r, g, b) = (255, (int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: // RGB (24-bit)
            (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8: // RRGGBBAA (32-bit)
            (a, r, g, b) = (int & 0xFF, int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF)
        default:
            (a, r, g, b) = (1, 1, 1, 0)
        }

        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue:  Double(b) / 255,
            opacity: Double(a) / 255
        )
    }
}

// MARK: - View Theme Extensions
extension View {
    /// Apply navy background - the main theme background used throughout the app
    func navyBackground() -> some View {
        self.background(Color.navy)
    }

    /// Apply glass card styling with consistent background and corner radius
    func glassCardStyle() -> some View {
        self
            .background(Color.white.opacity(0.08))
            .clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 12, style: .continuous)
                    .stroke(Color.white.opacity(0.12), lineWidth: 1)
            )
    }

    /// Apply primary text color (white)
    func primaryText() -> some View {
        self.foregroundStyle(Color.textPrimary)
    }

    /// Apply secondary text color
    func secondaryText() -> some View {
        self.foregroundStyle(Color.textSecondary)
    }

    /// Apply tertiary text color
    func tertiaryText() -> some View {
        self.foregroundStyle(Color.textTertiary)
    }
}
