import fs from "node:fs/promises";
import path from "node:path";

import { createTokenDictionary, repoRoot } from "../style-dictionary.config.mjs";

function getTokenValue(token) {
  if (token && typeof token === "object") {
    if ("value" in token) {
      return token.value;
    }
    if ("$value" in token) {
      return token.$value;
    }
  }
  return token;
}

function lowerHex(value) {
  if (typeof value === "string" && value.startsWith("#")) {
    return value.toLowerCase();
  }
  return value;
}

function swiftHex(value) {
  return String(value).toUpperCase();
}

function hexToRgbChannels(value) {
  const match = /^#?([0-9a-fA-F]{6})$/.exec(String(value));
  if (!match) {
    throw new Error(`Expected 6-digit hex color, got: ${value}`);
  }

  const hex = match[1];
  return [
    Number.parseInt(hex.slice(0, 2), 16),
    Number.parseInt(hex.slice(2, 4), 16),
    Number.parseInt(hex.slice(4, 6), 16),
  ];
}

function rgbaFromHex(value, alpha) {
  const [red, green, blue] = hexToRgbChannels(value);
  return `rgba(${red}, ${green}, ${blue}, ${alpha})`;
}

function walk(root, segments) {
  return segments.reduce((current, segment) => current[segment], root);
}

function token(root, ...segments) {
  return getTokenValue(walk(root, segments));
}

function tokenObject(root, ...segments) {
  return walk(root, segments);
}

function parseFontFamilyList(value) {
  return String(value)
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function jsString(value) {
  return JSON.stringify(value);
}

function formatTsObject(obj, indent = 0) {
  const entries = Object.entries(obj);
  const pad = " ".repeat(indent);
  const innerPad = " ".repeat(indent + 2);

  const lines = entries.map(([key, value]) => {
    const keySource = /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) ? key : jsString(key);
    if (Array.isArray(value)) {
      return `${innerPad}${keySource}: [${value.map((item) => jsString(item)).join(", ")}],`;
    }
    if (value && typeof value === "object") {
      return `${innerPad}${keySource}: ${formatTsObject(value, indent + 2)},`;
    }
    if (typeof value === "number") {
      return `${innerPad}${keySource}: ${value},`;
    }
    return `${innerPad}${keySource}: ${jsString(value)},`;
  });

  return `{\n${lines.join("\n")}\n${pad}}`;
}

function formatCss(tokens) {
  const brandKeys = ["navy", "blue", "green", "red", "gold"];
  const scaleKeys = ["navy", "blue", "green", "heart", "gray"];
  const scaleSteps = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"];
  const spacingKeys = ["0", "1", "2", "3", "4", "5", "6", "8", "10", "12", "16", "20", "24"];
  const fontSizeKeys = ["xs", "sm", "base", "lg", "xl", "2xl", "3xl", "4xl", "5xl"];
  const fontWeightKeys = ["light", "normal", "medium", "semibold", "bold"];
  const lineHeightKeys = ["tight", "snug", "normal", "relaxed", "loose"];
  const radiusKeys = ["none", "sm", "base", "md", "lg", "xl", "2xl", "full"];
  const shadowKeys = ["sm", "base", "md", "lg", "xl"];
  const zIndexKeys = [
    "hide",
    "auto",
    "base",
    "docked",
    "dropdown",
    "sticky",
    "banner",
    "overlay",
    "modal",
    "popover",
    "skipLink",
    "toast",
    "tooltip",
  ];
  const breakpointKeys = ["sm", "md", "lg", "xl", "2xl"];

  const lines = [
    "/**",
    " * Generated by frontend/scripts/build-tokens.mjs",
    " * Source authoring tree: /tokens",
    " * Do not edit this file by hand.",
    " */",
    "",
    ":root {",
    "  color-scheme: light;",
    "",
    "  /* Canonical PulsePlate brand tokens */",
  ];

  for (const key of brandKeys) {
    lines.push(`  --pp-${key}: ${lowerHex(token(tokens, "color", "brand", key))};`);
  }

  lines.push("", "  /* Foundation color scales */");
  for (const scale of scaleKeys) {
    for (const step of scaleSteps) {
      lines.push(`  --color-${scale}-${step}: ${lowerHex(token(tokens, "color", "scale", scale, step))};`);
    }
    lines.push("");
  }
  lines.pop();

  lines.push("", "  /* Base UI semantic tokens */");
  const semanticMap = [
    ["--color-primary", token(tokens, "semantic", "color", "primary")],
    ["--color-primary-foreground", token(tokens, "semantic", "color", "primaryForeground")],
    ["--color-bg", token(tokens, "semantic", "color", "bg")],
    ["--color-surface", token(tokens, "semantic", "color", "surface")],
    ["--color-surface-muted", token(tokens, "semantic", "color", "surfaceMuted")],
    ["--color-border", token(tokens, "semantic", "color", "border")],
    ["--color-text", token(tokens, "semantic", "color", "text")],
    ["--color-text-muted", token(tokens, "semantic", "color", "textMuted")],
    ["--color-success", token(tokens, "semantic", "color", "success")],
    ["--color-warning", token(tokens, "semantic", "color", "warning")],
    ["--color-error", token(tokens, "semantic", "color", "error")],
    ["--color-info", token(tokens, "semantic", "color", "info")],
    ["--color-focus", token(tokens, "semantic", "color", "focus")],
    ["--color-focus-rgb", token(tokens, "semantic", "color", "focusRgb")],
    ["--color-focus-shadow", token(tokens, "semantic", "color", "focusShadow")],
  ];
  for (const [name, value] of semanticMap) {
    lines.push(`  ${name}: ${lowerHex(value)};`);
  }

  const destructiveHex = lowerHex(token(tokens, "semantic", "color", "error"));
  lines.push(
    "  --color-destructive: var(--color-error);",
    `  --color-destructive-foreground: ${destructiveHex};`,
    `  --color-destructive-bg: ${rgbaFromHex(destructiveHex, 0.1)};`,
    `  --color-destructive-bg-hover: ${rgbaFromHex(destructiveHex, 0.14)};`,
    `  --color-destructive-border: ${rgbaFromHex(destructiveHex, 0.18)};`,
    `  --color-destructive-shadow-color: ${rgbaFromHex(destructiveHex, 0.12)};`,
    "  --shadow-destructive: 0 12px 32px var(--color-destructive-shadow-color);"
  );

  lines.push("", "  /* Legacy aliases (compatibility only) */");
  const legacyAliasEntries = [
    ["--pp-primary", token(tokens, "platform", "web", "legacyAlias", "primary")],
    ["--pp-accent", token(tokens, "platform", "web", "legacyAlias", "accent")],
    ["--pp-text", token(tokens, "platform", "web", "legacyAlias", "text")],
    ["--pp-muted", token(tokens, "platform", "web", "legacyAlias", "muted")],
    ["--pp-radius-xl", token(tokens, "platform", "web", "legacyAlias", "radiusXl")],
    ["--pp-space-2", token(tokens, "platform", "web", "legacyAlias", "space2")],
    ["--pp-space-3", token(tokens, "platform", "web", "legacyAlias", "space3")],
  ];
  for (const [name, value] of legacyAliasEntries) {
    lines.push(`  ${name}: ${value};`);
  }

  lines.push("", "  /* Spacing */");
  for (const key of spacingKeys) {
    lines.push(`  --spacing-${key}: ${token(tokens, "spacing", key)};`);
  }
  lines.push(`  --spacing-touch: ${token(tokens, "spacing", "touch")};`);
  lines.push(`  --spacing-touch-large: ${token(tokens, "spacing", "touchLarge")};`);
  lines.push(`  --spacing-button-sm: ${token(tokens, "spacing", "button", "sm")};`);
  lines.push(`  --spacing-button-md: ${token(tokens, "spacing", "button", "md")};`);
  lines.push(`  --spacing-button-lg: ${token(tokens, "spacing", "button", "lg")};`);
  lines.push(`  --spacing-input-sm: ${token(tokens, "spacing", "input", "sm")};`);
  lines.push(`  --spacing-input-md: ${token(tokens, "spacing", "input", "md")};`);
  lines.push(`  --spacing-input-lg: ${token(tokens, "spacing", "input", "lg")};`);

  lines.push("", "  /* Typography */");
  lines.push(`  --font-family-base: ${token(tokens, "typography", "fontFamily", "sans")};`);
  for (const key of fontSizeKeys) {
    lines.push(`  --font-size-${key}: ${token(tokens, "typography", "fontSize", key)};`);
  }
  for (const key of fontWeightKeys) {
    lines.push(`  --font-weight-${key}: ${token(tokens, "typography", "fontWeight", key)};`);
  }
  for (const key of lineHeightKeys) {
    lines.push(`  --line-height-${key}: ${token(tokens, "typography", "lineHeight", key)};`);
  }

  lines.push("", "  /* Radius */");
  for (const key of radiusKeys) {
    lines.push(`  --radius-${key}: ${token(tokens, "radius", key)};`);
  }

  lines.push("", "  /* Shadows */");
  for (const key of shadowKeys) {
    lines.push(`  --shadow-${key}: ${token(tokens, "shadow", key)};`);
  }

  lines.push("", "  /* Motion */");
  lines.push(`  --motion-fast: ${token(tokens, "motion", "duration", "fast")};`);
  lines.push(`  --motion-standard: ${token(tokens, "motion", "duration", "standard")};`);
  lines.push(`  --motion-slow: ${token(tokens, "motion", "duration", "slow")};`);
  lines.push(`  --motion-spring-response: ${token(tokens, "motion", "spring", "response")};`);
  lines.push(`  --motion-spring-damping: ${token(tokens, "motion", "spring", "damping")};`);

  lines.push("", "  /* Z-index */");
  for (const key of zIndexKeys) {
    const cssName = key === "skipLink" ? "skip-link" : key.toLowerCase();
    lines.push(`  --z-${cssName}: ${token(tokens, "zIndex", key)};`);
  }

  lines.push("", "  /* Breakpoints */");
  for (const key of breakpointKeys) {
    lines.push(`  --breakpoint-${key}: ${token(tokens, "breakpoint", key)};`);
  }
  lines.push("", "  /* Native control highlight */");
  lines.push(`  accent-color: ${token(tokens, "platform", "web", "nativeAccentColor")};`);
  lines.push("}", "", ":root {");

  const darkMap = [
    ["--color-primary-dark", token(tokens, "semantic", "dark", "primary")],
    ["--color-primary-foreground-dark", token(tokens, "semantic", "dark", "primaryForeground")],
    ["--color-bg-dark", token(tokens, "semantic", "dark", "bg")],
    ["--color-surface-dark", token(tokens, "semantic", "dark", "surface")],
    ["--color-surface-muted-dark", token(tokens, "semantic", "dark", "surfaceMuted")],
    ["--color-border-dark", token(tokens, "semantic", "dark", "border")],
    ["--color-text-dark", token(tokens, "semantic", "dark", "text")],
    ["--color-text-muted-dark", token(tokens, "semantic", "dark", "textMuted")],
    ["--color-success-dark", token(tokens, "semantic", "dark", "success")],
    ["--color-warning-dark", token(tokens, "semantic", "dark", "warning")],
    ["--color-error-dark", token(tokens, "semantic", "dark", "error")],
    ["--color-info-dark", token(tokens, "semantic", "dark", "info")],
    ["--color-focus-dark", token(tokens, "semantic", "dark", "focus")],
    ["--color-focus-dark-rgb", token(tokens, "semantic", "dark", "focusRgb")],
    ["--color-focus-shadow-dark", token(tokens, "semantic", "dark", "focusShadow")],
    ["--shadow-sm-dark", token(tokens, "shadow", "dark", "sm")],
    ["--shadow-base-dark", token(tokens, "shadow", "dark", "base")],
    ["--shadow-md-dark", token(tokens, "shadow", "dark", "md")],
    ["--shadow-lg-dark", token(tokens, "shadow", "dark", "lg")],
    ["--shadow-xl-dark", token(tokens, "shadow", "dark", "xl")],
  ];
  for (const [name, value] of darkMap) {
    lines.push(`  ${name}: ${lowerHex(value)};`);
  }
  lines.push(
    "}",
    "",
    "html[data-theme=\"dark\"] {",
    "  color-scheme: dark;",
    "  --color-primary: var(--color-primary-dark);",
    "  --color-primary-foreground: var(--color-primary-foreground-dark);",
    "  --color-bg: var(--color-bg-dark);",
    "  --color-surface: var(--color-surface-dark);",
    "  --color-surface-muted: var(--color-surface-muted-dark);",
    "  --color-border: var(--color-border-dark);",
    "  --color-text: var(--color-text-dark);",
    "  --color-text-muted: var(--color-text-muted-dark);",
    "  --color-success: var(--color-success-dark);",
    "  --color-warning: var(--color-warning-dark);",
    "  --color-error: var(--color-error-dark);",
    "  --color-info: var(--color-info-dark);",
    "  --color-focus: var(--color-focus-dark);",
    "  --color-focus-rgb: var(--color-focus-dark-rgb);",
    "  --color-focus-shadow: var(--color-focus-shadow-dark);",
    "  --shadow-sm: var(--shadow-sm-dark);",
    "  --shadow-base: var(--shadow-base-dark);",
    "  --shadow-md: var(--shadow-md-dark);",
    "  --shadow-lg: var(--shadow-lg-dark);",
    "  --shadow-xl: var(--shadow-xl-dark);",
    "}",
    "",
    "html[data-theme=\"light\"] {",
    "  color-scheme: light;",
    "}"
  );

  lines.push(
    "",
    "@media (prefers-color-scheme: dark) {",
    "  html:not([data-theme=\"light\"]) {",
    "    color-scheme: dark;",
    "    --color-primary: var(--color-primary-dark);",
    "    --color-primary-foreground: var(--color-primary-foreground-dark);",
    "    --color-bg: var(--color-bg-dark);",
    "    --color-surface: var(--color-surface-dark);",
    "    --color-surface-muted: var(--color-surface-muted-dark);",
    "    --color-border: var(--color-border-dark);",
    "    --color-text: var(--color-text-dark);",
    "    --color-text-muted: var(--color-text-muted-dark);",
    "    --color-success: var(--color-success-dark);",
    "    --color-warning: var(--color-warning-dark);",
    "    --color-error: var(--color-error-dark);",
    "    --color-info: var(--color-info-dark);",
    "    --color-focus: var(--color-focus-dark);",
    "    --color-focus-rgb: var(--color-focus-dark-rgb);",
    "    --color-focus-shadow: var(--color-focus-shadow-dark);",
    "    --shadow-sm: var(--shadow-sm-dark);",
    "    --shadow-base: var(--shadow-base-dark);",
    "    --shadow-md: var(--shadow-md-dark);",
    "    --shadow-lg: var(--shadow-lg-dark);",
    "    --shadow-xl: var(--shadow-xl-dark);",
    "  }",
    "}",
    ""
  );

  return `${lines.join("\n")}`;
}

function formatTs(tokens) {
  const brand = {
    navy: lowerHex(token(tokens, "color", "brand", "navy")),
    blue: lowerHex(token(tokens, "color", "brand", "blue")),
    green: lowerHex(token(tokens, "color", "brand", "green")),
    red: lowerHex(token(tokens, "color", "brand", "red")),
    gold: lowerHex(token(tokens, "color", "brand", "gold")),
  };

  const colors = {
    navy: Object.fromEntries(
      ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"].map((step) => [
        step,
        lowerHex(token(tokens, "color", "scale", "navy", step)),
      ])
    ),
    blue: Object.fromEntries(
      ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"].map((step) => [
        step,
        lowerHex(token(tokens, "color", "scale", "blue", step)),
      ])
    ),
    green: Object.fromEntries(
      ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"].map((step) => [
        step,
        lowerHex(token(tokens, "color", "scale", "green", step)),
      ])
    ),
    heart: Object.fromEntries(
      ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"].map((step) => [
        step,
        lowerHex(token(tokens, "color", "scale", "heart", step)),
      ])
    ),
    gray: Object.fromEntries(
      ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"].map((step) => [
        step,
        lowerHex(token(tokens, "color", "scale", "gray", step)),
      ])
    ),
    semantic: {
      success: "canonicalBrand.green",
      warning: lowerHex(token(tokens, "semantic", "color", "warning")),
      error: "canonicalBrand.red",
      info: "canonicalBrand.blue",
    },
  };

  const spacing = {
    0: token(tokens, "spacing", "0"),
    1: token(tokens, "spacing", "1"),
    2: token(tokens, "spacing", "2"),
    3: token(tokens, "spacing", "3"),
    4: token(tokens, "spacing", "4"),
    5: token(tokens, "spacing", "5"),
    6: token(tokens, "spacing", "6"),
    8: token(tokens, "spacing", "8"),
    10: token(tokens, "spacing", "10"),
    12: token(tokens, "spacing", "12"),
    16: token(tokens, "spacing", "16"),
    20: token(tokens, "spacing", "20"),
    24: token(tokens, "spacing", "24"),
    touch: token(tokens, "spacing", "touch"),
    touchLarge: token(tokens, "spacing", "touchLarge"),
    button: {
      sm: token(tokens, "spacing", "button", "sm"),
      md: token(tokens, "spacing", "button", "md"),
      lg: token(tokens, "spacing", "button", "lg"),
    },
    input: {
      sm: token(tokens, "spacing", "input", "sm"),
      md: token(tokens, "spacing", "input", "md"),
      lg: token(tokens, "spacing", "input", "lg"),
    },
  };

  const typography = {
    fontFamily: {
      sans: parseFontFamilyList(token(tokens, "typography", "fontFamily", "sans")),
      mono: parseFontFamilyList(token(tokens, "typography", "fontFamily", "mono")),
    },
    fontSize: {
      xs: token(tokens, "typography", "fontSize", "xs"),
      sm: token(tokens, "typography", "fontSize", "sm"),
      base: token(tokens, "typography", "fontSize", "base"),
      lg: token(tokens, "typography", "fontSize", "lg"),
      xl: token(tokens, "typography", "fontSize", "xl"),
      "2xl": token(tokens, "typography", "fontSize", "2xl"),
      "3xl": token(tokens, "typography", "fontSize", "3xl"),
      "4xl": token(tokens, "typography", "fontSize", "4xl"),
      "5xl": token(tokens, "typography", "fontSize", "5xl"),
    },
    fontWeight: {
      light: token(tokens, "typography", "fontWeight", "light"),
      normal: token(tokens, "typography", "fontWeight", "normal"),
      medium: token(tokens, "typography", "fontWeight", "medium"),
      semibold: token(tokens, "typography", "fontWeight", "semibold"),
      bold: token(tokens, "typography", "fontWeight", "bold"),
    },
    lineHeight: {
      tight: token(tokens, "typography", "lineHeight", "tight"),
      snug: token(tokens, "typography", "lineHeight", "snug"),
      normal: token(tokens, "typography", "lineHeight", "normal"),
      relaxed: token(tokens, "typography", "lineHeight", "relaxed"),
      loose: token(tokens, "typography", "lineHeight", "loose"),
    },
    textStyles: {
      heading: getTokenValue(tokenObject(tokens, "typography", "textStyle", "heading")),
      body: getTokenValue(tokenObject(tokens, "typography", "textStyle", "body")),
      caption: getTokenValue(tokenObject(tokens, "typography", "textStyle", "caption")),
    },
  };

  const borderRadius = {
    none: token(tokens, "radius", "none"),
    sm: token(tokens, "radius", "sm"),
    base: token(tokens, "radius", "base"),
    md: token(tokens, "radius", "md"),
    lg: token(tokens, "radius", "lg"),
    xl: token(tokens, "radius", "xl"),
    "2xl": token(tokens, "radius", "2xl"),
    full: token(tokens, "radius", "full"),
  };

  const shadows = {
    sm: token(tokens, "shadow", "sm"),
    base: token(tokens, "shadow", "base"),
    md: token(tokens, "shadow", "md"),
    lg: token(tokens, "shadow", "lg"),
    xl: token(tokens, "shadow", "xl"),
  };

  const breakpoints = {
    sm: token(tokens, "breakpoint", "sm"),
    md: token(tokens, "breakpoint", "md"),
    lg: token(tokens, "breakpoint", "lg"),
    xl: token(tokens, "breakpoint", "xl"),
    "2xl": token(tokens, "breakpoint", "2xl"),
  };

  const zIndex = {
    hide: token(tokens, "zIndex", "hide"),
    auto: token(tokens, "zIndex", "auto"),
    base: token(tokens, "zIndex", "base"),
    docked: token(tokens, "zIndex", "docked"),
    dropdown: token(tokens, "zIndex", "dropdown"),
    sticky: token(tokens, "zIndex", "sticky"),
    banner: token(tokens, "zIndex", "banner"),
    overlay: token(tokens, "zIndex", "overlay"),
    modal: token(tokens, "zIndex", "modal"),
    popover: token(tokens, "zIndex", "popover"),
    skipLink: token(tokens, "zIndex", "skipLink"),
    toast: token(tokens, "zIndex", "toast"),
    tooltip: token(tokens, "zIndex", "tooltip"),
  };

  return `/**
 * Generated by frontend/scripts/build-tokens.mjs
 * Source authoring tree: /tokens
 * Do not edit this file by hand.
 */

export const canonicalBrand = ${formatTsObject(brand)} as const;

/**
 * @deprecated Use canonicalBrand.* directly in new code.
 * Kept only for soft migration compatibility.
 */
export const legacyBrandAliases = {
  primary: canonicalBrand.blue,
  accent: canonicalBrand.green,
} as const;

export const colors = {
  navy: ${formatTsObject(colors.navy, 2)},
  blue: ${formatTsObject(colors.blue, 2)},
  green: ${formatTsObject(colors.green, 2)},
  heart: ${formatTsObject(colors.heart, 2)},
  gray: ${formatTsObject(colors.gray, 2)},
  semantic: {
    success: canonicalBrand.green,
    warning: ${jsString(colors.semantic.warning)},
    error: canonicalBrand.red,
    info: canonicalBrand.blue,
  },
} as const;

export const spacing = ${formatTsObject(spacing)} as const;

export const typography = ${formatTsObject(typography)} as const;

export const borderRadius = ${formatTsObject(borderRadius)} as const;

export const shadows = ${formatTsObject(shadows)} as const;

export const breakpoints = ${formatTsObject(breakpoints)} as const;

export const zIndex = ${formatTsObject(zIndex)} as const;

export type ColorScale = keyof typeof colors.navy;
export type SpacingKey = keyof typeof spacing;
export type TypographySize = keyof typeof typography.fontSize;
export type TypographyWeight = keyof typeof typography.fontWeight;
`;
}

function swiftColorExpression(value) {
  if (typeof value !== "string") {
    return String(value);
  }
  if (value === "Color.white") {
    return value;
  }
  if (value.startsWith("Color.white.opacity")) {
    return value;
  }
  if (value.startsWith("#")) {
    return `Color(hex: "${swiftHex(value)}")`;
  }
  return value;
}

function swiftSemanticColorExpression(value, brandHexes) {
  if (typeof value !== "string") {
    return String(value);
  }

  if (value.startsWith("Color.")) {
    return value;
  }

  const normalized = value.toUpperCase();
  for (const [brandName, brandHex] of Object.entries(brandHexes)) {
    if (normalized === brandHex.toUpperCase()) {
      return `Brand.${brandName}`;
    }
  }

  if (normalized === "#FFFFFF") {
    return "Color.white";
  }

  return swiftColorExpression(value);
}

function durationMsToSecondsLiteral(value) {
  const milliseconds = Number.parseFloat(String(value).replace("ms", ""));
  return (milliseconds / 1000).toFixed(2).replace(/0+$/, "").replace(/\.$/, "");
}

function formatSwift(tokens) {
  const brandHexes = {
    navy: token(tokens, "color", "brand", "navy"),
    blue: token(tokens, "color", "brand", "blue"),
    green: token(tokens, "color", "brand", "green"),
    red: token(tokens, "color", "brand", "red"),
    gold: token(tokens, "color", "brand", "gold"),
  };

  const assetNames = {
    navy: token(tokens, "platform", "ios", "asset", "navy"),
    blue: token(tokens, "platform", "ios", "asset", "blue"),
    green: token(tokens, "platform", "ios", "asset", "green"),
    red: token(tokens, "platform", "ios", "asset", "red"),
    gold: token(tokens, "platform", "ios", "asset", "gold"),
  };

  const iosSemantic = {
    success: token(tokens, "semantic", "color", "success"),
    warning: token(tokens, "semantic", "color", "warning"),
    error: token(tokens, "semantic", "color", "error"),
    info: token(tokens, "semantic", "color", "info"),
    primary: token(tokens, "semantic", "color", "primary"),
    primaryForeground: token(tokens, "semantic", "color", "primaryForeground"),
    textPrimary: token(tokens, "platform", "ios", "semantic", "textPrimary"),
    textSecondary: token(tokens, "platform", "ios", "semantic", "textSecondary"),
    textTertiary: token(tokens, "platform", "ios", "semantic", "textTertiary"),
    surface: token(tokens, "platform", "ios", "semantic", "surface"),
    surfaceElevated: token(tokens, "platform", "ios", "semantic", "surfaceElevated"),
    surfaceHighlight: token(tokens, "platform", "ios", "semantic", "surfaceHighlight"),
    strokeSubtle: token(tokens, "platform", "ios", "semantic", "strokeSubtle"),
  };

  const iosSpacing = Object.fromEntries(
    Object.keys(tokenObject(tokens, "platform", "ios", "spacing")).map((key) => [
      key,
      token(tokens, "platform", "ios", "spacing", key),
    ])
  );
  const iosTypography = Object.fromEntries(
    Object.keys(tokenObject(tokens, "platform", "ios", "typography")).map((key) => [
      key,
      token(tokens, "platform", "ios", "typography", key),
    ])
  );
  const iosRadius = Object.fromEntries(
    Object.keys(tokenObject(tokens, "platform", "ios", "radius")).map((key) => [
      key,
      token(tokens, "platform", "ios", "radius", key),
    ])
  );
  const iosElevation = Object.fromEntries(
    Object.keys(tokenObject(tokens, "platform", "ios", "elevation")).map((key) => [
      key,
      token(tokens, "platform", "ios", "elevation", key),
    ])
  );

  return `import SwiftUI

// Generated by frontend/scripts/build-tokens.mjs from /tokens
// Do not edit this file by hand.
enum GeneratedDesignTokens {
    enum BrandAsset {
        static let navy = "${assetNames.navy}"
        static let blue = "${assetNames.blue}"
        static let green = "${assetNames.green}"
        static let red = "${assetNames.red}"
        static let gold = "${assetNames.gold}"
    }

    enum Brand {
        static let navy = Color(BrandAsset.navy)
        static let blue = Color(BrandAsset.blue)
        static let green = Color(BrandAsset.green)
        static let red = Color(BrandAsset.red)
        static let gold = Color(BrandAsset.gold)
    }

    enum ColorToken {
        static let success = ${swiftSemanticColorExpression(iosSemantic.success, brandHexes)}
        static let warning = ${swiftSemanticColorExpression(iosSemantic.warning, brandHexes)}
        static let error = ${swiftSemanticColorExpression(iosSemantic.error, brandHexes)}
        static let info = ${swiftSemanticColorExpression(iosSemantic.info, brandHexes)}

        static let textPrimary = ${swiftColorExpression(iosSemantic.textPrimary)}
        static let textSecondary = ${swiftColorExpression(iosSemantic.textSecondary)}
        static let textTertiary = ${swiftColorExpression(iosSemantic.textTertiary)}

        static let surface = ${swiftColorExpression(iosSemantic.surface)}
        static let surfaceElevated = ${swiftColorExpression(iosSemantic.surfaceElevated)}
        static let surfaceHighlight = ${swiftColorExpression(iosSemantic.surfaceHighlight)}
        static let strokeSubtle = ${swiftColorExpression(iosSemantic.strokeSubtle)}

        static let primary = ${swiftSemanticColorExpression(iosSemantic.primary, brandHexes)}
        static let primaryForeground = ${swiftSemanticColorExpression(iosSemantic.primaryForeground, brandHexes)}
    }

    enum Spacing {
        static let xxSmall: CGFloat = ${iosSpacing.xxSmall}
        static let xSmall: CGFloat = ${iosSpacing.xSmall}
        static let small: CGFloat = ${iosSpacing.small}
        static let medium: CGFloat = ${iosSpacing.medium}
        static let large: CGFloat = ${iosSpacing.large}
        static let xLarge: CGFloat = ${iosSpacing.xLarge}
        static let xxLarge: CGFloat = ${iosSpacing.xxLarge}

        static let touchTarget: CGFloat = ${iosSpacing.touchTarget}
        static let touchTargetLarge: CGFloat = ${iosSpacing.touchTargetLarge}

        static let buttonPaddingSmall: CGFloat = ${iosSpacing.buttonPaddingSmall}
        static let buttonPaddingMedium: CGFloat = ${iosSpacing.buttonPaddingMedium}
        static let buttonPaddingLarge: CGFloat = ${iosSpacing.buttonPaddingLarge}

        static let inputPaddingSmall: CGFloat = ${iosSpacing.inputPaddingSmall}
        static let inputPaddingMedium: CGFloat = ${iosSpacing.inputPaddingMedium}
        static let inputPaddingLarge: CGFloat = ${iosSpacing.inputPaddingLarge}
    }

    enum Typography {
        static let sizeXS: CGFloat = ${iosTypography.sizeXS}
        static let sizeSM: CGFloat = ${iosTypography.sizeSM}
        static let sizeBase: CGFloat = ${iosTypography.sizeBase}
        static let sizeLG: CGFloat = ${iosTypography.sizeLG}
        static let sizeXL: CGFloat = ${iosTypography.sizeXL}
        static let size2XL: CGFloat = ${iosTypography.size2XL}
        static let size3XL: CGFloat = ${iosTypography.size3XL}
        static let size4XL: CGFloat = ${iosTypography.size4XL}

        static let caption = Font.system(size: sizeXS, weight: .regular)
        static let captionStrong = Font.system(size: sizeXS, weight: .semibold)
        static let body = Font.system(size: sizeBase, weight: .regular)
        static let bodyStrong = Font.system(size: sizeBase, weight: .semibold)
        static let title = Font.system(size: sizeLG, weight: .semibold)
        static let heading = Font.system(size: size2XL, weight: .bold)
        static let largeTitle = Font.system(size: size3XL, weight: .bold)
    }

    enum Radius {
        static let none: CGFloat = ${iosRadius.none}
        static let small: CGFloat = ${iosRadius.small}
        static let base: CGFloat = ${iosRadius.base}
        static let medium: CGFloat = ${iosRadius.medium}
        static let large: CGFloat = ${iosRadius.large}
        static let xLarge: CGFloat = ${iosRadius.xLarge}
        static let full: CGFloat = ${iosRadius.full}
    }

    enum Elevation {
        static let none: CGFloat = ${iosElevation.none}
        static let card: CGFloat = ${iosElevation.card}
        static let dropdown: CGFloat = ${iosElevation.dropdown}
        static let modal: CGFloat = ${iosElevation.modal}
        static let popover: CGFloat = ${iosElevation.popover}
    }

    enum Motion {
        static let fast: Double = ${durationMsToSecondsLiteral(token(tokens, "motion", "duration", "fast"))}
        static let standard: Double = ${durationMsToSecondsLiteral(token(tokens, "motion", "duration", "standard"))}
        static let slow: Double = ${durationMsToSecondsLiteral(token(tokens, "motion", "duration", "slow"))}

        static let springResponse: Double = ${token(tokens, "motion", "spring", "response")}
        static let springDamping: Double = ${token(tokens, "motion", "spring", "damping")}
    }
}
`;
}

async function writeIfChanged(targetPath, content) {
  const current = await fs.readFile(targetPath, "utf8").catch(() => null);
  if (current === content) {
    return;
  }
  await fs.writeFile(targetPath, content, "utf8");
}

async function main() {
  const trackedTargets = [
    path.join(repoRoot, "frontend", "src", "styles", "tokens.css"),
    path.join(repoRoot, "frontend", "src", "styles", "tokens.ts"),
    path.join(repoRoot, "ios", "PulsePlate", "DesignSystem", "DesignTokens.generated.swift"),
  ];
  const checkMode = process.argv.includes("--check");
  const readTrackedTargets = async () =>
    Promise.all(
      trackedTargets.map((targetPath) => fs.readFile(targetPath, "utf8").catch(() => ""))
    );

  async function buildOnce() {
    const dictionary = createTokenDictionary();
    await dictionary.hasInitialized;
    const tokens = dictionary.tokens;

    await writeIfChanged(
      path.join(repoRoot, "frontend", "src", "styles", "tokens.css"),
      formatCss(tokens)
    );
    await writeIfChanged(
      path.join(repoRoot, "frontend", "src", "styles", "tokens.ts"),
      formatTs(tokens)
    );
    await writeIfChanged(
      path.join(repoRoot, "ios", "PulsePlate", "DesignSystem", "DesignTokens.generated.swift"),
      formatSwift(tokens)
    );
  }

  if (!checkMode) {
    await buildOnce();
    return;
  }

  const before = await readTrackedTargets();
  await buildOnce();
  const afterFirstBuild = await readTrackedTargets();

  if (JSON.stringify(before) !== JSON.stringify(afterFirstBuild)) {
    throw new Error(
      "Generated design token artifacts are stale. Run the token build and commit the updated outputs."
    );
  }

  await buildOnce();
  const afterSecondBuild = await readTrackedTargets();

  if (JSON.stringify(afterFirstBuild) !== JSON.stringify(afterSecondBuild)) {
    throw new Error("Design token build is not deterministic across consecutive runs.");
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
