#!/usr/bin/env bash
set -euo pipefail

# Add Lottie animations (.json files) into the app bundle and generate Swift constants
# Usage: ./ios/add_lottie_animations.sh /path/to/animation1.json /path/to/animation2.json

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_RES_DIR="$ROOT_DIR/PulsePlate/Resources/Lottie"
GEN_DIR="$ROOT_DIR/PulsePlate/Generated"
GEN_SWIFT_FILE="$GEN_DIR/LottieAssets.swift"

mkdir -p "$TARGET_RES_DIR" "$GEN_DIR"

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 file1.json [file2.json ...]" >&2
  exit 1
fi

copied_basenames=()

sanitize_swift_identifier() {
  local name="$1"
  name="${name//[^a-zA-Z0-9_]/_}"
  if [[ $name =~ ^[0-9] ]]; then
    name="_${name}"
  fi
  echo "$name"
}

for src in "$@"; do
  if [ ! -f "$src" ]; then
    echo "❌ File not found: $src" >&2
    exit 1
  fi
  ext="${src##*.}"
  shopt -s nocasematch
  if [[ ! "$ext" =~ ^(json)$ ]]; then
    echo "⚠️ Skipping unsupported file (only .json): $src" >&2
    continue
  fi
  shopt -u nocasematch

  base_with_ext="$(basename "$src")"
  dest="$TARGET_RES_DIR/$base_with_ext"
  cp -f "$src" "$dest"

  base_no_ext="${base_with_ext%.*}"
  copied_basenames+=("$base_no_ext")
  echo "✅ Copied: $base_with_ext → $TARGET_RES_DIR"

done

# Also include any existing .json files already in the folder
while IFS= read -r -d '' f; do
  bn="$(basename "$f")";
  bn_no_ext="${bn%.*}";
  if [[ " ${copied_basenames[*]} " != *" $bn_no_ext "* ]]; then
    copied_basenames+=("$bn_no_ext")
  fi
done < <(find "$TARGET_RES_DIR" -maxdepth 1 -type f -iname "*.json" -print0)

# Sort unique
mapfile -t copied_basenames < <(printf '%s\n' "${copied_basenames[@]}" | awk '!seen[$0]++' | sort -f)

# Generate Swift enum with names (without extensions)
cat > "$GEN_SWIFT_FILE" << 'SWIFT'
// This file is auto-generated by add_lottie_animations.sh. Do not edit manually.
import Foundation

public enum LottieAssets: String, CaseIterable {
SWIFT

for name in "${copied_basenames[@]}"; do
  swift_id="$(sanitize_swift_identifier "$name")"
  echo "    case $swift_id = \"$name\"" >> "$GEN_SWIFT_FILE"
done

cat >> "$GEN_SWIFT_FILE" << 'SWIFT'
}

public extension LottieAssets {
    static var allNames: [String] { Self.allCases.map { $0.rawValue } }
}
SWIFT

echo "\n🎉 Generated: $GEN_SWIFT_FILE"
echo "   Cases: ${#copied_basenames[@]} (${copied_basenames[*]})"

echo "\nNext steps:"
echo "- Open Xcode and build. The files in Resources/Lottie will be embedded into the app bundle."
echo "- Use them via LottieAnimation.named(\"animation_name\"), e.g.: LottieAnimation.named(LottieAssets.fitchef_blink.rawValue)"
