#!/bin/bash
# 🔐 Authentication guide for Claude Code teleport sessions

echo "🔐 Claude Code Teleport Authentication"
echo "======================================"
echo ""
echo "Для использования --teleport нужна аутентификация через Claude.ai аккаунт."
echo "API ключ недостаточен для web sessions."
echo ""
echo "📋 Шаги:"
echo ""
echo "1. Запустите интерактивную сессию:"
echo "   claude"
echo ""
echo "2. В сессии выполните:"
echo "   /login"
echo ""
echo "3. Следуйте инструкциям для входа"
echo ""
echo "4. Проверьте статус:"
echo "   /status"
echo ""
echo "5. Используйте teleport:"
echo "   claude --teleport session_011CUtfGCXHFvi2LbfpXwUP5"
echo ""
