#!/usr/bin/env bash
# 🔐 Authentication guide for Claude Code teleport sessions
# Руководство по аутентификации для сессий Claude Code teleport

echo "🔐 Claude Code Teleport Authentication"
echo "======================================"
echo ""
echo "EN: To use --teleport, authentication via Claude.ai account is required."
echo "EN: API key alone is not sufficient for web sessions."
echo ""
echo "RU: Для использования --teleport нужна аутентификация через Claude.ai аккаунт."
echo "RU: API ключ недостаточен для web sessions."
echo ""
echo "📋 Steps / Шаги:"
echo ""
echo "EN: 1. Start an interactive session:"
echo "RU: 1. Запустите интерактивную сессию:"
echo "   claude"
echo ""
echo "EN: 2. In the session, execute:"
echo "RU: 2. В сессии выполните:"
echo "   /login"
echo ""
echo "EN: 3. Follow the instructions to log in"
echo "RU: 3. Следуйте инструкциям для входа"
echo ""
echo "EN: 4. Check status:"
echo "RU: 4. Проверьте статус:"
echo "   /status"
echo ""
echo "EN: 5. Use teleport:"
echo "RU: 5. Используйте teleport:"
echo "   claude --teleport session_011CUtfGCXHFvi2LbfpXwUP5"
echo ""
