# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Actionlint

on:
  pull_request:
    paths:
      - .github/workflows/**
  push:
    branches: [main]
    paths:
      - .github/workflows/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Lint workflows
        uses: rhysd/actionlint@a443f344ff32813837fa49f7aa6cbc478d770e62 # v1.7.9
