name: Docker Image CI
permissions:
  contents: read

on:
  push:
    branches: [ "main", "feat/**", "fix/**" ]
  pull_request:
    branches: [ "main", "feat/**", "fix/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "my-image-name:$(date +%s)"
