name: Docker Image CI

env:
  PULSEPLATE_PYTHON_INDEX_URL: ${{ vars.PULSEPLATE_PYTHON_INDEX_URL || secrets.PULSEPLATE_PYTHON_INDEX_URL }}
  PULSEPLATE_PYTHON_TRUSTED_HOST: ${{ vars.PULSEPLATE_PYTHON_TRUSTED_HOST || secrets.PULSEPLATE_PYTHON_TRUSTED_HOST }}

permissions:
  contents: read

on:
  push:
    branches: [ "main", "feat/**", "fix/**" ]
  pull_request:
    branches: [ "main", "feat/**", "fix/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --build-arg PULSEPLATE_PYTHON_INDEX_URL="${PULSEPLATE_PYTHON_INDEX_URL}" \
          --build-arg PULSEPLATE_PYTHON_TRUSTED_HOST="${PULSEPLATE_PYTHON_TRUSTED_HOST}" \
          --tag "my-image-name:$(date +%s)"
