import SwiftUI

// Generated by frontend/scripts/build-tokens.mjs from /tokens
// Do not edit this file by hand.
enum GeneratedDesignTokens {
    enum BrandAsset {
        static let navy = "Navy"
        static let blue = "AppPrimary"
        static let green = "AccentGreen"
        static let red = "HeartRed"
        static let gold = "Gold"
    }

    enum Brand {
        static let navy = Color(BrandAsset.navy)
        static let blue = Color(BrandAsset.blue)
        static let green = Color(BrandAsset.green)
        static let red = Color(BrandAsset.red)
        static let gold = Color(BrandAsset.gold)
    }

    enum ColorToken {
        static let success = Brand.green
        static let warning = Color(hex: "#F59E0B")
        static let error = Brand.red
        static let info = Brand.blue

        static let textPrimary = Color.white
        static let textSecondary = Color.white.opacity(0.8)
        static let textTertiary = Color.white.opacity(0.6)

        static let surface = Color.white.opacity(0.1)
        static let surfaceElevated = Color.white.opacity(0.15)
        static let surfaceHighlight = Color.white.opacity(0.25)
        static let strokeSubtle = Color.white.opacity(0.12)

        static let primary = Brand.blue
        static let primaryForeground = Color.white
    }

    enum Spacing {
        static let xxSmall: CGFloat = 2
        static let xSmall: CGFloat = 4
        static let small: CGFloat = 8
        static let medium: CGFloat = 12
        static let large: CGFloat = 16
        static let xLarge: CGFloat = 24
        static let xxLarge: CGFloat = 32

        static let touchTarget: CGFloat = 44
        static let touchTargetLarge: CGFloat = 56

        static let buttonPaddingSmall: CGFloat = 8
        static let buttonPaddingMedium: CGFloat = 12
        static let buttonPaddingLarge: CGFloat = 16

        static let inputPaddingSmall: CGFloat = 8
        static let inputPaddingMedium: CGFloat = 12
        static let inputPaddingLarge: CGFloat = 16
    }

    enum Typography {
        static let sizeXS: CGFloat = 12
        static let sizeSM: CGFloat = 14
        static let sizeBase: CGFloat = 16
        static let sizeLG: CGFloat = 18
        static let sizeXL: CGFloat = 20
        static let size2XL: CGFloat = 24
        static let size3XL: CGFloat = 30
        static let size4XL: CGFloat = 36

        static let caption = Font.system(size: sizeXS, weight: .regular)
        static let captionStrong = Font.system(size: sizeXS, weight: .semibold)
        static let body = Font.system(size: sizeBase, weight: .regular)
        static let bodyStrong = Font.system(size: sizeBase, weight: .semibold)
        static let title = Font.system(size: sizeLG, weight: .semibold)
        static let heading = Font.system(size: size2XL, weight: .bold)
        static let largeTitle = Font.system(size: size3XL, weight: .bold)
    }

    enum Radius {
        static let none: CGFloat = 0
        static let small: CGFloat = 4
        static let base: CGFloat = 6
        static let medium: CGFloat = 8
        static let large: CGFloat = 12
        static let xLarge: CGFloat = 16
        static let full: CGFloat = 9999
    }

    enum Elevation {
        static let none: CGFloat = 0
        static let card: CGFloat = 2
        static let dropdown: CGFloat = 4
        static let modal: CGFloat = 8
        static let popover: CGFloat = 12
    }

    enum Motion {
        static let fast: Double = 0.15
        static let standard: Double = 0.25
        static let slow: Double = 0.4

        static let springResponse: Double = 0.3
        static let springDamping: Double = 0.7
    }
}
